jobs:
  
build:
runs-on: ubuntu-latest
 steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: ./my-app/package-lock.json # Point to subfolder lock file

      - name: Install dependencies
        run: npm install
        working-directory: ./my-app # Runs inside my-app folder

      - name: Build with Next.js
        run: npm run build
        working-directory: ./my-app # Runs build inside my-app folder
